### ISSUE TITLE
Audio Observation: Duolingo.com + AirPods Max

### ISSUE THREAD

**Issue by Anonymous1845973** [mozilla/cubeb#699] opened 2022-03-26 01:10 UTC
I've recently bought a pair of Apple AirPods Max (APM).

I learn Spanish on Duolingo daily, and while using the APM I noticed a static noise when the language was spoken back through Firefox v 98.0.1 running Mac OS 11.6.1 

The static didn't replicate in any other instance, and was isolated to Firefox.

Today I've used the APM in Chrome to use Duolingo and the static did not replicate.

Evidently there is an audio compression issue or bug in Firefox - I have emailed the engineers at Duolingo as Im curious as to why this is, no response yet.

If anyone can explain WHY on the above basis, I would love to learn.

Hopefully this serves someone in the future that may also come across this! Still continue to use and support Firefox.

**Comment by kinetiknz** [comment] 2022-03-26 01:17
Thanks for filing a bug!  It's possible this is [bug 1714448](https://bugzilla.mozilla.org/show_bug.cgi?id=1714448).  It's probably best to file a new bug against Firefox regarding your issue, as the underlying cause may be anywhere from Duolingo's app to somewhere within Firefox.

**Comment by jaredkhan** [comment] 2022-04-18 21:13
I have been experiencing something very similar with Duolingo on Mac OS 12.3, regardless of what speakers I use. It is not just at the beginning of the audio file but throughout so unlikely to be a duplicate of that one, @kinetiknz

I was googling trying to figure out what text-to-speech they use, since it didn't sound like the system one, and came across 'Amazon Polly'. Sure enough, if I generate a file with this Amazon Polly test app: https://ai-service-demos.go-aws.com/polly it has this irksome buzzing behaviour on Firefox 99.0.1 but not Safari or Chrome.

**Reproduction files outside of Duolingo context**

- Here's the .mp3 file I generated (in a .zip so GitHub lets me upload it):
[speech.mp3.zip](https://github.com/mozilla/cubeb/files/8508160/speech.mp3.zip)
- Here's it in an <audio> tag so it can be played in Safari for comparison:
[speech_crackle_test_app.zip](https://github.com/mozilla/cubeb/files/8508159/speech_crackle_test_app.zip)

Possibly related bug on the tracker: [crackles while playing audio samples on duolingo.com website in Ubuntu](https://bugzilla.mozilla.org/show_bug.cgi?id=1764161)

@Anonymous1845973, did you open a bug with Firefox?

**Comment by Anonymous1845973** [comment] 2022-04-19 01:41
@jaredkhan doesn't look I did direct, reported the bug here and on r/Firefox on Reddit

**Comment by kinetiknz** [comment] 2022-04-19 06:59
Thanks, having a sample file will make debugging much easier.  If you're still experiencing this issue in Firefox 100 onwards, that confirms this isn't the same issue as bug 1714448.

Let's use https://bugzilla.mozilla.org/show_bug.cgi?id=1764161 for the Firefox bug.

**Comment by jaredkhan** [comment] 2022-04-19 08:04
Ah yeah my bad, if I get the pre-release version 100, this problem goes away both for the file I shared and, as far as I can tell, Duolingo in general. Cheers!

**Comment by padenot** [comment] 2022-04-19 08:33
I'm closing this, because it was not a cubeb bug (and it's already fixed in Firefox). Thanks for reporting and confirming that it's fixed!

**Closed by padenot** 2022-04-19 08:33 UTC
